name: CI - Train Model and Build Image

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout code + DVC
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies (for OpenCV etc.)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Install DVC and pull data
      run: |
        pip install dvc
        dvc pull

    - name: Preprocess Data
      run: python src/preprocess.py

    - name: Train Model
      run: python src/train.py --epochs 2

    - name: Run Unit Tests
      run: pytest tests/ -v

    - name: Save Model for Build
      run: |
        mkdir -p models/
        cp models/dogs_cats_cnn.keras models/

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dogs-vs-cats-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/dogs-vs-cats-api:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max